version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: example.com/php
    container_name: app
    restart: unless-stopped
    volumes:
    - ./:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    ports:
    - "4307:3306"
    volumes:
    - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

