version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: example.com/php
    container_name: app
    restart: unless-stopped
    volumes:
    - ./:/var/www
    - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

